if [ "$1" = "16" ]
then
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l el -r WJets" -S el -I "-s " 
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l el -r WJets" -S mc -I "-s "
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -r WJets" -S mu -I "-s "
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -r WJets" -S mc -I "-s "
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l el -r QCD" -S el -I "-s "
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l el -r QCD" -S mc -I "-s " 
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -r QCD" -S mu -I "-s "
    ./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -r QCD" -S mc -I "-s "
   # ./SubmitQJob.py -C FullCut -Y 16 -T "-l el" -S el -I "-s " 
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l el" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l mu" -S mu -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l mu" -S mc -I "-s "
    
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l el -e JER_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l el -e JER_dn" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l el -e JEC_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l el -e JEC_dn" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -e JER_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -e JER_dn" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -e JEC_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 16 -T "-l mu -e JEC_dn" -S mc -I "-s "
elif [ "$1" = "17" ]
then
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l el -r WJets" -S el -I "-s " 
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l el -r WJets" -S mc -I "-s "
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -r WJets" -S mu -I "-s "
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -r WJets" -S mc -I "-s "
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l el -r QCD" -S el -I "-s "
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l el -r QCD" -S mc -I "-s " 
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -r QCD" -S mu -I "-s "
    ./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -r QCD" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l el" -S el -I "-s " 
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l el" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l mu" -S mu -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l mu" -S mc -I "-s "
    
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l el -e JER_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l el -e JER_dn" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l el -e JEC_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l el -e JEC_dn" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -e JER_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -e JER_dn" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -e JEC_up" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 17 -T "-l mu -e JEC_dn" -S mc -I "-s "
elif [ "$1" = "18" ]
then
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l el -r WJets" -S el -I "-s " 
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l el -r WJets" -S mc -I "-s "
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l mu -r WJets" -S mu -I "-s "
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l mu -r WJets" -S mc -I "-s "
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l el -r QCD" -S el -I "-s "
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l el -r QCD" -S mc -I "-s " 
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l mu -r QCD" -S mu -I "-s "
    ./SubmitQJob.py -C FullCut -Y 18 -T "-l mu -r QCD" -S mc -I "-s "
   # ./SubmitQJob.py -C FullCut -Y 18 -T "-l el" -S el -I "-s " 
    #./SubmitQJob.py -C FullCut -Y 18 -T "-l el" -S mc -I "-s "
    #./SubmitQJob.py -C FullCut -Y 18 -T "-l mu" -S mu -I "-s "
    #./SubmitQJob.py -C FullCut -Y 18 -T "-l mu" -S mc -I "-s "
    
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l el -e JER_up" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l el -e JER_dn" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l el -e JEC_up" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l el -e JEC_dn" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l mu -e JER_up" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l mu -e JER_dn" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l mu -e JEC_up" -S mc -I "-s "
    #./SubmitCondorJob.py -C FullCut -Y 18 -T "-l mu -e JEC_dn" -S mc -I "-s "
fi
