nohup ./submitJob.py -C MakeHist -T "-l mu -u 20 -e lepton_dn -o 150" -S samplelst -R 70 > makehist_mu_lepton_dn.out&
nohup ./submitJob.py -C MakeHist -T "-l el -u 20 -e lepton_dn -o 150" -S samplelst -R 70 > makehist_el_lepton_dn.out&
nohup ./submitJob.py -C MakeHist -T "-l mu -u 20 -e lepton_up -o 150" -S samplelst -R 70 > makehist_mu_lepton_up.out&
nohup ./submitJob.py -C MakeHist -T "-l el -u 20 -e lepton_up -o 150" -S samplelst -R 70 > makehist_el_lepton_up.out&
nohup ./submitJob.py -C MakeHist -T "-l mu -u 20 -e b-tag_dn -o 150"  -S samplelst -R 70 > makehist_mu_b-tag_dn.out&
nohup ./submitJob.py -C MakeHist -T "-l el -u 20 -e b-tag_dn -o 150"  -S samplelst -R 70 > makehist_el_b-tag_dn.out&
nohup ./submitJob.py -C MakeHist -T "-l mu -u 20 -e b-tag_up -o 150"  -S samplelst -R 70 > makehist_mu_b-tag_up.out&
nohup ./submitJob.py -C MakeHist -T "-l el -u 20 -e b-tag_up -o 150"  -S samplelst -R 70 > makehist_el_b-tag_up.out&
nohup ./submitJob.py -C MakeHist -T "-l mu -u 20 -e TopPt_dn -o 150"  -S samplelst -R 70 > makehist_mu_TopPt_dn.out&
nohup ./submitJob.py -C MakeHist -T "-l el -u 20 -e TopPt_dn -o 150"  -S samplelst -R 70 > makehist_el_TopPt_dn.out&
