python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty bctag_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty bctag_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty FR_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty FR_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty FSR_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty FSR_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty ISR_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty ISR_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty JEC_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty JEC_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty JER_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty JER_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty lepton_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty lepton_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty lighttag_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty lighttag_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty muFmuR_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty muFmuR_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty PDF_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty PDF_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty pileup_up
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty pileup_dn
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty resolution_10
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty resolution_-10
python PlotAcp.py -y 17 -l co -c 20 -o 150 -s ttbar_dtg5 -B --uncertainty woTopPT
